#!/usr/bin/env python3
r"""
figures/mock_data.py — the Paper-1 sensitivity-table CONTRACT, plus a synthetic
generator so the Fig 2-5 renderers can be built and reviewed before the real
FEM solves land.

============================  READ THIS FIRST  ============================
EVERY NUMBER THIS SCRIPT WRITES IS SYNTHETIC. It is not a solve result, it is
not a measurement, and it must never be quoted, screenshotted, or copied into
the paper. Its only job is to exercise the plotting code against a realistic
*shape* of data. The output file carries `_MOCK` in its name and a
`# SYNTHETIC` banner as its first line; every figure rendered from it is
stamped with a diagonal "SYNTHETIC — MOCK DATA" watermark. Do not defeat any
of these markers.
==========================================================================

THE CONTRACT  (results/04_sensitivity.csv)
------------------------------------------
One row per (electrode, muscle, condition, mesh). The real analysis stage
(`src/04_analyze.py`, owned by the solve pipeline — NOT by this file) is
expected to emit the same schema so the renderers switch from mock to real by
changing one path.

Core columns — these six are the contract as specified:

    electrode        str   electrode/site name, must match results/02_electrode_positions.csv
    muscle           str   articulator-muscle name, must match src/config.py MUSCLES
    condition        str   {"iso", "aniso"}     isotropic vs anisotropic muscle sigma
    mesh             str   {"truncated", "extended"}   native vs neck-extended mesh
    lead_field       float median |E . n_hat| inside the compartment, V/m per mA,
                           reciprocity solve, median taken over the orientation sweep
    db_rel_best_jaw  float 20*log10(lead_field / max_over_jaw_sites(lead_field))
                           computed WITHIN each (muscle, condition, mesh) group.
                           The best jaw site for a muscle is 0 dB by construction;
                           every other site is relative to it (usually negative).

Extension columns written here so the renderers can read EVERYTHING from the one
CSV (see note below). Flagged explicitly rather than smuggled in:

    distance_mm      float electrode-to-compartment Euclidean distance (mm).
                           *** REQUIRED BY Fig 3 (attenuation vs distance). ***
                           There is no way to plot attenuation-vs-distance from
                           the six core columns alone, so the contract is
                           extended by exactly this one measured column. When the
                           real 04_analyze.py runs it must emit distance_mm too,
                           or Fig 3 has no x-axis.
    montage          str   {"jaw","ear","ceegrid","reference"} — denormalized from
                           the electrode name (src/config.py MONTAGES). Convenience
                           only: render_common re-derives it from config if a real
                           CSV omits it, so a bare six-column file still renders
                           Figs 2/4/5.
    muscle_group     str   {"suprahyoid","tongue","mastication","labial","cervical"}
                           — denormalized from src/config.py MUSCLES. Same
                           convenience/derivable status as `montage`.

WHY THE EXTENSION COLUMNS. The task specifies "each [renderer] reading only the
CSV." Distance is genuinely absent from the six core columns yet Fig 3 needs it,
so it is added as a measured column and flagged here and in the commit message.
`montage`/`muscle_group` are pure naming conventions (recoverable from config);
they are written so the mock is self-describing, and render_common tolerates
their absence in a real file.

Row count: 24 electrodes x 18 muscles x 2 conditions = 864 rows. The `mesh`
column is populated with "extended" (the production mesh) throughout; the
"truncated" block is what the boundary/neck-extension run appends later. The
renderers already filter on `mesh` (default "extended"), so nothing changes for
them when that second block arrives.

Reads (generator only — renderers never do this): src/config.py for the muscle
and montage vocabulary, and results/02_electrode_positions.csv for real
electrode coordinates so the synthetic distances are anatomically plausible.

    simnibs_python figures/mock_data.py            # writes results/04_sensitivity_MOCK.csv
    simnibs_python figures/mock_data.py --out /tmp/foo.csv --seed 7
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))
import config  # noqa: E402  (repo convention: figures import the shared config)

BANNER = (
    "# SYNTHETIC MOCK DATA — generated by figures/mock_data.py. "
    "NOT a solve result. Do not quote. Regenerate with: simnibs_python figures/mock_data.py"
)

# ----------------------------------------------------------------------
# SYNTHETIC muscle compartment centroids, RAS mm, right side.
# These are hand-placed to be ANATOMICALLY PLAUSIBLE, not measured — MIDA
# centroids require the label volume this generator does not load. They exist
# only so electrode-to-muscle distances (and therefore the attenuation trend in
# Fig 3) look like real geometry: the mastoid/styloid/temporalis muscles sit
# near the ear cluster, the labial/tongue muscles sit far and anterior. Every
# coordinate here is invented.
# ----------------------------------------------------------------------
_SYNTH_MUSCLE_CENTROID = {
    # suprahyoid
    "digastric_posterior": (55.0, -8.0, -35.0),   # posterior belly at mastoid notch — near ear
    "stylohyoid":          (46.0, -2.0, -38.0),    # styloid process — near ear
    "mylohyoid":           (6.0, 55.0, -95.0),     # floor of mouth, anterior
    "geniohyoid":          (3.0, 60.0, -98.0),     # anterior deep
    "digastric_anterior":  (9.0, 66.0, -100.0),    # anterior belly
    # tongue
    "genioglossus":        (4.0, 55.0, -70.0),     # deep central
    "hyoglossus":          (18.0, 45.0, -78.0),
    "styloglossus":        (40.0, 15.0, -55.0),    # styloid origin — moderate
    # mastication
    "masseter":            (58.0, 48.0, -55.0),    # 1-2 cm anterior to tragus
    "temporalis":          (68.0, 18.0, 25.0),     # directly above the ear
    "medial_pterygoid":    (30.0, 30.0, -60.0),    # deep
    "lateral_pterygoid":   (42.0, 28.0, -42.0),    # deep, near TMJ
    # labial
    "orbicularis_oris":    (2.0, 95.0, -60.0),     # far anterior
    "buccinator":          (40.0, 68.0, -62.0),
    "mentalis":            (4.0, 92.0, -95.0),
    "depressor_anguli_oris": (30.0, 78.0, -88.0),
    # cervical
    "platysma":            (35.0, 30.0, -95.0),    # broad superficial sheet
    "sternocleidomastoid": (55.0, -5.0, -70.0),    # mastoid attachment but extends inferiorly
}

# A couple of electrodes have no measured coordinate yet in
# results/02_electrode_positions.csv (throat_scm is HELD). Give them a
# plausible synthetic position so the 24-electrode grid is complete.
_SYNTH_ELECTRODE_COORD = {
    "throat_scm": (52.0, -2.0, -95.0),   # over SCM, lower neck — SYNTHETIC placeholder
}


def _electrode_table() -> pd.DataFrame:
    """Electrode name -> montage + RAS coordinate, from the real positions CSV
    where available, synthetic fallback where held."""
    pos = pd.read_csv(config.RESULTS / "02_electrode_positions.csv")
    # montage from config so the vocabulary is the single source of truth
    montage_of = {}
    for mont, names in config.MONTAGES.items():
        for n in names:
            montage_of[n] = mont
    montage_of[config.REFERENCE] = "reference"
    montage_of[config.BIAS] = "reference"

    rows = []
    for name in montage_of:                      # iterate the 24 known sites
        r = pos.loc[pos["name"] == name]
        if len(r) and np.isfinite(r["R"].iloc[0]):
            R, A, S = float(r["R"].iloc[0]), float(r["A"].iloc[0]), float(r["S"].iloc[0])
        elif name in _SYNTH_ELECTRODE_COORD:
            R, A, S = _SYNTH_ELECTRODE_COORD[name]
        else:
            raise SystemExit(f"no coordinate for electrode {name!r} and no synthetic fallback")
        rows.append((name, montage_of[name], R, A, S))
    return pd.DataFrame(rows, columns=["electrode", "montage", "R", "A", "S"])


def generate(seed: int = 20260802) -> pd.DataFrame:
    rng = np.random.default_rng(seed)

    elecs = _electrode_table()
    muscles = [(name, group) for name, group, _lab, _exp in config.MUSCLES]
    pca_muscles = set(config.FIBRE_PCA_MUSCLES)

    # per-muscle source strength and volume-conduction decay length (synthetic)
    base = {m: rng.uniform(0.55, 1.15) for m, _ in muscles}
    lam = {m: rng.uniform(24.0, 40.0) for m, _ in muscles}          # mm
    # per-muscle anisotropy multiplier applied ONLY to PCA-modelled muscles.
    # Isotropic-in-both-runs muscles get exactly 1.0 so aniso == iso for them,
    # which is what makes those rows read as "no change" in Fig 4.
    aniso_gain = {
        m: (rng.uniform(0.70, 1.35) if m in pca_muscles else 1.0)
        for m, _ in muscles
    }

    centroids = {m: np.array(_SYNTH_MUSCLE_CENTROID[m]) for m, _ in muscles}
    ecoord = {r.electrode: np.array([r.R, r.A, r.S]) for r in elecs.itertuples()}

    records = []
    for m, group in muscles:
        for e in elecs.itertuples():
            d = float(np.linalg.norm(ecoord[e.electrode] - centroids[m]))
            # isotropic lead field: decay with distance x per-muscle strength x noise
            noise = float(rng.lognormal(mean=0.0, sigma=0.12))
            lf_iso = base[m] * np.exp(-d / lam[m]) * noise
            # anisotropic: per-muscle gain (topography-preserving) plus a small
            # per-(electrode,muscle) perturbation so Fig 4 has texture not a flat step
            perturb = 1.0 + (aniso_gain[m] - 1.0) * float(rng.uniform(0.6, 1.0)) \
                if m in pca_muscles else 1.0
            lf_aniso = lf_iso * perturb
            records.append((e.electrode, e.montage, m, group, "iso", "extended", d, lf_iso))
            records.append((e.electrode, e.montage, m, group, "aniso", "extended", d, lf_aniso))

    df = pd.DataFrame(
        records,
        columns=["electrode", "montage", "muscle", "muscle_group",
                 "condition", "mesh", "distance_mm", "lead_field"],
    )

    # db_rel_best_jaw: within each (muscle, condition, mesh) group, the loudest
    # jaw site is the 0 dB reference for that muscle.
    def _db(group: pd.DataFrame) -> pd.Series:
        jaw = group.loc[group["montage"] == "jaw", "lead_field"]
        ref = float(jaw.max()) if len(jaw) else float(group["lead_field"].max())
        return 20.0 * np.log10(group["lead_field"] / ref)

    df["db_rel_best_jaw"] = (
        df.groupby(["muscle", "condition", "mesh"], sort=False, group_keys=False)
          .apply(_db, include_groups=False)
    )

    # column order: six core columns first, then the flagged extensions
    df = df[[
        "electrode", "muscle", "condition", "mesh", "lead_field", "db_rel_best_jaw",
        "distance_mm", "montage", "muscle_group",
    ]]
    df["lead_field"] = df["lead_field"].round(6)
    df["db_rel_best_jaw"] = df["db_rel_best_jaw"].round(3)
    df["distance_mm"] = df["distance_mm"].round(2)
    return df


def write(df: pd.DataFrame, out: Path) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    with open(out, "w", newline="", encoding="utf-8") as fh:
        fh.write(BANNER + "\n")
        df.to_csv(fh, index=False)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(prog="mock_data.py", description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", type=Path,
                    default=config.RESULTS / "04_sensitivity_MOCK.csv",
                    help="output CSV (distinct name; never the real 04_sensitivity.csv)")
    ap.add_argument("--seed", type=int, default=20260802)
    a = ap.parse_args(argv)

    if a.out.name == "04_sensitivity.csv":
        raise SystemExit("refusing to write the real contract filename; use a _MOCK name")

    df = generate(a.seed)
    write(df, a.out)

    n_e = df["electrode"].nunique()
    n_m = df["muscle"].nunique()
    print("=" * 70)
    print("  SYNTHETIC MOCK DATA — NOT A SOLVE RESULT — do not quote")
    print("=" * 70)
    print(f"  wrote {len(df)} rows  ({n_e} electrodes x {n_m} muscles x "
          f"{df['condition'].nunique()} conditions x {df['mesh'].nunique()} mesh)")
    print(f"  -> {a.out}")
    print(f"  lead_field range      : {df['lead_field'].min():.4f} .. {df['lead_field'].max():.4f} V/m per mA")
    print(f"  db_rel_best_jaw range : {df['db_rel_best_jaw'].min():.1f} .. {df['db_rel_best_jaw'].max():.1f} dB")
    print(f"  distance_mm range     : {df['distance_mm'].min():.1f} .. {df['distance_mm'].max():.1f} mm")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
